// USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
// CART
export const TOGGLE_CART_DISPLAY = 'TOGGLE_CART_DISPLAY';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const DECREASE_ITEM = 'DECREASE_ITEM';
// SHOP
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';
